/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function CarCollections(props) {
  const { nodes, materials } = useGLTF('./carModel/Collection_r3f.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.57, 0, 0]} scale={0.01}>
        <group
          position={[-2.09, -0.27, -53.26]}
          rotation={[-1.57, 0.02, -0.03]}
          scale={100}
        >
          <mesh
            geometry={nodes.Body_1.geometry}
            material={materials.Curve_Black}
          />
          <mesh
            geometry={nodes.Body_2.geometry}
            material={materials.Curve_Black}
          />
        </group>
        <mesh
          geometry={nodes.Ground.geometry}
          material={materials.Material}
          rotation={[-1.57, 0, 0]}
          scale={[158.92, 270.48, 291.43]}
        />
        <mesh
          geometry={nodes.Tire_Vent.geometry}
          material={materials.Black}
          position={[0, 0, -1.28]}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={19.16}
        position={[-17.93, 11.49, 26.41]}
        rotation={[-0.42, -0.56, -0.23]}
      />
    </group>
  )
}

useGLTF.preload('./carModel/Collection_r3f.gltf')
