/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import MatcapMaterial from './matcapMaterial'
// import { useControls } from 'leva'

export default function CarComponent(props) {
  const { nodes } = useGLTF('./carModel/Curve_r3f.gltf')

  // const controls = useControls({
  //   position: {
  //     value: [0, 0, 0],
  //     step: 0.1,
  //   },
  //   scale: {
  //     value: [1, 1, 1],
  //     step: 0.1,
  //   },
  //   rotation: {
  //     value: [0, 0, 0],
  //     step: 0.1,
  //   },
  //   color: '#ff6d63',
  // })

  return (
    <group {...props} dispose={null}>
      <group
        rotation={[1.57, 0, 0.3]}
        scale={0.01}
        position={[0.5, -0.5, -0.5]}
      >
        {/* change car position */}
        <group position={[0, 80, -25.7]} rotation={[0, 0, -0.6]} scale={1}>
          <group
            position={[-2.09, -0.27, -53.26]}
            rotation={[-1.57, 0.02, -0.03]}
            scale={100}
          >
            <mesh
              geometry={nodes.网格007.geometry}
              material={MatcapMaterial()}
            />
            <mesh
              geometry={nodes.网格007_1.geometry}
              material={MatcapMaterial()}
            />
          </group>
          <mesh
            geometry={nodes.Tire_Vent.geometry}
            // material={materials.Black}
            material={MatcapMaterial()}
            position={[0, 0, -1.28]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./carModel/Curve_r3f.gltf')
